### ISSUE TITLE
wait_for_update should be at least 100ms

### ISSUE THREAD

**Issue by Zhankevich** [vallonic/consent-studio-gtm-template#2]
When reviewing your template, we've noticed that wait_for_update was set to a default less than 500 milliseconds. When specifying this it's a best practice to give some buffer time to attempt to allow for the updateConsent command to be fired. This is very important when loading the consent management script dynamically.

**Comment by thierrymaasdam** [comment]
@Zhankevich, thank you for this recommendation as well. As mentioned in #1, I have now set it to 500 ms. I was wondering, though: is your recommendation for it to be at least 100 ms or 500 ms? I believe that with 500 ms we're in the clear nevertheless.
